load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "keys",
    srcs = glob([
        "jvm/*.kt",
    ]),
    visibility = ["//mediarecorder:__subpackages__"]
)
